version: "3.8"

services:
  app:
    image: node
    container_name: node_qci_app
    ports:
      - "4000:4000"
    volumes:
      - .:/qci-app
    environment:
      - NODE_ENV=development

  db:
    image: mariadb
    container_name: DATABASES
    ports:
      - "3306:3306"
    logging:
      driver: none
    environment:
      - MARIADB_DATABASE="DBQualityGate"
      - MARIADB_USER="marcos"
      - MARIADB_PASSWORD="marcos123"
      - MARIADB_ROOT_PASSWORD="root123"
