version: "3.8"

services:
  app:
    image: node
    container_name: linksweb
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development

  db:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    logging:
      driver: none
    environment:
      - MYSQL_DATABASE=database
      - MYSQL_USER="user"
      - MYSQL_PASSWORD="password"
      - MYSQL_ROOT_PASSWORD="root_password"
